[platformio]
src_dir = .

[env:T-Echo]
platform = nordicnrf52
board = nrf52840_dk_adafruit
framework = arduino

lib_extra_dirs =
  ../libraries

lib_compat_mode = strict

lib_ignore =
  arduino-basicmac
  Basicmac LoRaWAN stack
  arduino-lmic
  IBM LMIC framework
  bcm2835
  C and C++ support for Broadcom BCM 2835
  EasyLink
  EEPROM
  ESP8266TrueRandom
  SCSerial
  SimpleNetwork
  STM32duino Low Power
  STM32duino RTC
  WS2812
  AXP202X_Library
  Exp_SoftwareSerial
  Exp_EspSoftwareSerial
  FT5206_Library
  Sqlite3Esp32
  TFT_eSPI
  toneAC
  XPowersLib
  ESP8266FtpServer
  nRF905
  NeoPixelBus
  NeoPixelBus by Makuna

build_flags =
  -I.
  -I../libraries/OGN
  -I../libraries/ESP32_I2C_Bus
  -I../libraries/PCF8563_Library/src
  -I../libraries/Seeed_Arduino_AHT20/src
  -I../libraries/Adafruit-GFX-Library/Fonts
  -I$PROJECT_PACKAGES_DIR/framework-arduinoadafruitnrf52/libraries/Wire
  -include protocol.h
  -DSERIAL_TX_BUFFER_SIZE=256
  -DSERIAL_RX_BUFFER_SIZE=256

extra_scripts =
  pre:scripts/platformio_hooks.py

; The firmware is intended to be copied manually to the T-Echo bootloader
; mass-storage drive, so no upload protocol is configured here.

[env:T-Beam-Supreme]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

lib_extra_dirs =
  ../libraries

lib_compat_mode = strict

lib_ignore =
  arduino-basicmac
  Basicmac LoRaWAN stack
  arduino-NVM
  Bluefruit52_BLEUart_HM10
  bcm2835
  C and C++ support for Broadcom BCM 2835
  EasyLink
  EEPROM
  ESP8266TrueRandom
  SCSerial
  SimpleNetwork
  STM32duino Low Power
  STM32duino RTC
  TFT_eSPI
  WS2812
  nRF905
  NeoPixelBus
  NeoPixelBus by Makuna

build_flags =
  -I.
  -I../libraries/OGN
  -I../libraries/XPowersLib/src
  -I../libraries/PCF8563_Library/src
  -I../libraries/ESP32_I2C_Bus
  -I../libraries/Adafruit-GFX-Library/Fonts
  -include protocol.h
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DEXCLUDE_TFT
  -DEXCLUDE_SD_CARD
  -DEXCLUDE_IMU
  -DEXCLUDE_VOICE

extra_scripts =
  pre:scripts/platformio_hooks.py

upload_protocol = esptool
