#if !defined(_RADIOLIB_LR11X0_FIRMWARE_H)
#define _RADIOLIB_LR11X0_FIRMWARE_H

#if defined(RADIOLIB_LR1110_FIRMWARE_IN_RAM)
  #define RADIOLIB_LR1110_FIRMWARE_ATTR
#else
  #define RADIOLIB_LR1110_FIRMWARE_ATTR   RADIOLIB_NONVOLATILE
#endif

#define RADIOLIB_LR11X0_FIRMWARE_IMAGE_SIZE LR11XX_FIRMWARE_IMAGE_SIZE

#error "No LR11x0 firmware images available!"

#endif
